# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

orbs:
   heroku: circleci/heroku@1.2.6

jobs:
  build-test-analyze:
     working_directory: ~/Test
     docker:
          - image: cimg/openjdk:11.0
          - image: circleci/postgres:9.6.2-alpine
            auth:
              username: dajana27
              password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
            environment:
              POSTGRES_USER: postgres
              POSTGRES_DB: fishermandb

     steps:
          - checkout:
              path: ~/Test
          - run:
              name: Build
              command: mvn -B -DskipTests clean package
          - run:
              name: Test
              command: mvn test
          - run: 
              name: Analyze on SonarCloud
              command: mvn verify sonar:sonar -Dsonar.projectKey=Dajana11-99_Test
workflows:
  deploy-workflow:
    jobs:
      - build-test-analyze
      - heroku/deploy-via-git:
          name: deploy-backend
          app-name: Fisherman-back
          filters:
            branches:
              only:
                - main
          requires:
            - build-test-analyze
      - heroku/deploy-via-git:
          name: deploy-frontend
          app-name: Fisherman-front
          filters:
            branches:
              only:
                - main
          requires:
            - deploy-backend
